version: '3'
services:
  web:
        image: web-cgi:latest
        build: .
        container_name: "web-cgi"
        hostname: "web-cgi"
        volumes:
          - "./abc:/home/abc"
        ports:
          - 58080:80
        environment:
          - RUN_USER=abc
        tty: true
